/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/signup_owner`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin/admin_approval_dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/owner/owner_dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/user/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/owner/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/signup_owner`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/admin_approval_dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/owner/owner_dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/user/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/owner/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/explore${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/signup_owner${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/admin/admin_approval_dashboard${`?${string}` | `#${string}` | ''}` | `/owner/owner_dashboard${`?${string}` | `#${string}` | ''}` | `/user/dashboard${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/signup_owner`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin/admin_approval_dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/owner/owner_dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/user/dashboard`; params?: Router.UnknownInputParams; } | `/owner/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/owner/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
